const GLOBAL_CONSTANTS = {
  VERSION: "v0.0.1",
  PORT: process.env.PORT,
  API_KEY_HUBSPOT: process.env.API_KEY_HUBSPOT,
  MASTER_KEY_TOKEN: process.env.MASTER_KEY_TOKEN,
  OFFSET: process.env.OFFSET,
  USER_DATABASE: process.env.USER_DATABASE,
  PASS_DATABASE: process.env.PASS_DATABASE,
  SERVER_DATABASE: process.env.SERVER_DATABASE,
  DATABASE_NAME: process.env.DATABASE_NAME,
  DATABASE_PORT: 1433,
  KEY_GET_PARAMETERS: process.env.KEY_GET_PARAMETERS,
  KEY_MANDRILL: process.env.KEY_MANDRILL,
  KEY_ENROLL_CONFIG: process.env.KEY_ENROLL_CONFIG,
  DATABASE_LOGS: process.env.DATABASE_LOGS,
  LOG_DOCUMENT_WARNING: process.env.LOG_DOCUMENT_WARNING,
  LOG_DOCUMENT_ERROR: process.env.LOG_DOCUMENT_ERROR,
  KEY_SET_LOGIN_HISTORY: process.env.KEY_SET_LOGIN_HISTORY,
};

module.exports = GLOBAL_CONSTANTS;
