const GLOBAL_CONSTANTS = {
  VERSION: "v0.0.2",
  PORT: process.env.PORT,
  API_KEY_HUBSPOT: process.env.API_KEY_HUBSPOT,
  MASTER_KEY_TOKEN: process.env.MASTER_KEY_TOKEN,
  OFFSET: process.env.OFFSET,
  USER_DATABASE: process.env.USER_DATABASE,
  PASS_DATABASE: process.env.PASS_DATABASE,
  SERVER_DATABASE: process.env.SERVER_DATABASE,
  DATABASE_NAME: process.env.DATABASE_NAME,
  DATABASE_PORT: 1433,
  KEY_GET_PARAMETERS: process.env.KEY_GET_PARAMETERS,
  KEY_MANDRILL: process.env.KEY_MANDRILL,
  KEY_ENROLL_CONFIG: process.env.KEY_ENROLL_CONFIG,
  KEY_SET_LOGIN_HISTORY: process.env.KEY_SET_LOGIN_HISTORY,
  CLIENT_ID: process.env.CLIENT_ID,
  CLIENT_SECRET: process.env.CLIENT_SECRET,
  KEY_METAMAP_CONFIG: process.env.KEY_METAMAP_CONFIG,
  KEY_CUSTOMER_IN_DOCUMENT: process.env.KEY_CUSTOMER_IN_DOCUMENT,
  AWS_S3_ACCESS_KEY_ID: process.env.AWS_S3_ACCESS_KEY_ID,
  AWS_S3_SECRET_ACCESS_KEY: process.env.AWS_S3_SECRET_ACCESS_KEY,
  NODE_ENV: process.env.NODE_ENV,
  STREAM_LOG: process.env.STREAM_LOG,
  KEY_MESSAGE_SCHEDULED: process.env.KEY_MESSAGE_SCHEDULED
};

module.exports = GLOBAL_CONSTANTS;
